## Question: 
### Generate a random matrix of shape (1 million, 2) and perofm below operations:
#### 1. Find dist b/w each 2-dim data point from centroid of the dataset
#### 2. Append newly calculated distances as new column in dataset
#### 3. Given centroid, generate 3 closest neighbours from it
#### 4. Given any data point, generate 3 c losest neighbours from it

In [31]:
import numpy as np

#### Generating a random matrix with given shape

In [32]:
arr = np.random.randint(100, 2000, size=(1000000,2))
arr

array([[1541, 1108],
       [1172,  574],
       [ 833,  624],
       ...,
       [1681,  620],
       [1632,  946],
       [ 820,  766]])

#### Calculate centroid for the data and compute Euclidean dist

In [33]:
centroid = np.mean(arr, axis=0)
centroid

array([1049.188567, 1049.26622 ])

In [34]:
distances = np.sqrt(np.sum((arr-centroid)**2, axis=1))
distances

array([495.30610994, 490.87740623, 477.06273631, ..., 763.84237543,
       591.88941419, 364.3722693 ])

#### Add another column in the data

In [35]:
np.hstack([arr, distances.reshape(-1,1)])

array([[1541.        , 1108.        ,  495.30610994],
       [1172.        ,  574.        ,  490.87740623],
       [ 833.        ,  624.        ,  477.06273631],
       ...,
       [1681.        ,  620.        ,  763.84237543],
       [1632.        ,  946.        ,  591.88941419],
       [ 820.        ,  766.        ,  364.3722693 ]])

#### Get 3 closest distant points

In [36]:
arr[distances.argsort()][:3]

array([[1050, 1048],
       [1051, 1049],
       [1051, 1049]])